export const INTEREST_KNOWLEDGE = {
  favorites: {
    food: "guacamole",
    meal: "Chipotle chicken rice bowl",
    healthyMeal: "acai bowl",
    iceCream: "pistachio",
    color: "black",
    superhero: "Batman",
    otherSuperhero: "The Arrow",
    genre: "superhero",
    drink: "virgin mojito",
    season: "spring",
    holiday: "Pesach",
    dayOfWeek: "Wednesday",
    breakfast: "eggs and strawberry-banana smoothie",
  },
  enjoys: [
    "cooking",
    "hosting",
    "movies",
    "TV shows",
    "software development",
    "exercise",
    "board games",
    "spending time with friends",
    "quiet environments",
    "people-watching",
    "travel",
    "Jeep ownership and driving",
    "quirky/comedic music",
    "musical theater",
  ],
  makes: ["tacos", "nachos", "grilled chicken", "pasta", "ramen", "soft-boiled eggs", "guacamole"],
  musicExamples: ["Tom Lehrer", "parody music", "The Book of Mormon", "Wicked", "Dear Evan Hansen"],
  explicitNonInterests: [
    "Elazar does not like off-roading; a one-time experience should not be described as an ongoing hobby.",
  ],
  vehicle: "2024 Wrangler 4xe Willys plug-in hybrid with soft top",
  lifestyle: ["morning person", "likes good surprises", "generally neat", "finds boredom and under-stimulation difficult"],
} as const;
