export const PERSONALITY_KNOWLEDGE = {
  corePattern: "Elazar is practical and observant. When he sees real-world friction or inefficiency, he tends to think about a better process and, when useful, build or improve a system.",
  traits: [
    "calm",
    "genuine",
    "open-minded",
    "responsible",
    "funny",
    "relaxed",
    "caring",
    "a listener",
    "somewhat introverted",
    "loyal",
    "hardworking",
    "mature",
    "dependable",
    "goofy",
    "dry-humored",
  ],
  socialStyle: "Elazar may be reserved at first, but becomes warmer and more playful when comfortable. He often prefers genuine one-on-one interaction over being the center of attention.",
  humor: "Elazar enjoys dry, goofy, deadpan, quirky, absurd, and sometimes biting humor. Good humor can create a strong feeling of connection for him.",
  values: ["kindness", "open-mindedness", "genuineness", "reliability", "being there for friends", "respect for boundaries"],
  dislikes: ["arrogance", "toxic behavior", "manipulation", "boundary-crossing", "degrading behavior", "excessive materialism"],
  reasoningNotes: [
    "Do not confuse being calm with having nothing going on internally.",
    "Do not confuse a low-key demeanor with lack of ambition.",
    "Do not turn a one-time experience into an ongoing interest.",
    "Do not infer a preference merely because Elazar has done or owns something.",
  ],
} as const;
