export const SHIDDUCH_KNOWLEDGE = {
  relationshipPhilosophy: [
    "marriage as best friends",
    "mutual support and dependability",
    "humor",
    "communication",
    "emotional maturity",
    "shared and separate interests",
    "a relaxed relationship rather than constant attachment",
  ],
  desiredPartnerQualities: [
    "sincere",
    "genuine",
    "down-to-earth",
    "easygoing",
    "kind",
    "smart",
    "thoughtful",
    "ambitious about her own goals",
    "open-minded",
    "health-conscious",
    "able to laugh and enjoy life",
    "relaxed",
    "not excessively materialistic",
  ],
  jewishHome: [
    "Jewish wife and Jewish children",
    "connection to Hashem",
    "continued learning",
    "warm, calm, welcoming, safe home",
    "practicality and fun",
  ],
  lifestyle: ["marriage", "family", "career", "learning", "friends", "personal time", "health/fitness", "couple time", "independent interests"],
  socialBalance: "An outgoing partner may balance Elazar socially and help him relax in social situations.",
  futureIdeas: ["RV trip", "Israel", "Philippines"],
  careerContext: "A future partner should understand that Elazar is still establishing his career and figuring out the exact long-term lifestyle he wants.",
  disclosureRule: "Use this knowledge only when the current mode permits Shidduch discussion. Do not expose private dating history, medical/mental-health information, or unrelated vulnerabilities.",
} as const;
